version: '3.4'

services:
  dialysis.api:
    image: ${DOCKER_REGISTRY-}dialysis
    build:
      context: .
      dockerfile: Dialysis.API/Dockerfile
    depends_on:
        - dialysisdb
    networks:
        - dialysis-network

  dialysisdb:
    container_name: dialysisdb
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=MyPass@word"
    ports:
      - "1433:1433"
    hostname: dialysisdb
    networks:
        - dialysis-network

networks:
  dialysis-network:
    driver: bridge